/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrendsRouteImport } from './routes/trends'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReferralsRouteImport } from './routes/referrals'
import { Route as OfficeHoursRouteImport } from './routes/office-hours'
import { Route as MentorsRouteImport } from './routes/mentors'
import { Route as JourneyMapRouteImport } from './routes/journey-map'
import { Route as HeatmapRouteImport } from './routes/heatmap'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as ChallengesRouteImport } from './routes/challenges'
import { Route as CareerGpsRouteImport } from './routes/career-gps'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'

const TrendsRoute = TrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralsRoute = ReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeHoursRoute = OfficeHoursRouteImport.update({
  id: '/office-hours',
  path: '/office-hours',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorsRoute = MentorsRouteImport.update({
  id: '/mentors',
  path: '/mentors',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyMapRoute = JourneyMapRouteImport.update({
  id: '/journey-map',
  path: '/journey-map',
  getParentRoute: () => rootRouteImport,
} as any)
const HeatmapRoute = HeatmapRouteImport.update({
  id: '/heatmap',
  path: '/heatmap',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesRoute = ChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerGpsRoute = CareerGpsRouteImport.update({
  id: '/career-gps',
  path: '/career-gps',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/career-gps': typeof CareerGpsRoute
  '/challenges': typeof ChallengesRoute
  '/community': typeof CommunityRoute
  '/heatmap': typeof HeatmapRoute
  '/journey-map': typeof JourneyMapRoute
  '/mentors': typeof MentorsRoute
  '/office-hours': typeof OfficeHoursRoute
  '/referrals': typeof ReferralsRoute
  '/settings': typeof SettingsRoute
  '/stories': typeof StoriesRoute
  '/trends': typeof TrendsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/career-gps': typeof CareerGpsRoute
  '/challenges': typeof ChallengesRoute
  '/community': typeof CommunityRoute
  '/heatmap': typeof HeatmapRoute
  '/journey-map': typeof JourneyMapRoute
  '/mentors': typeof MentorsRoute
  '/office-hours': typeof OfficeHoursRoute
  '/referrals': typeof ReferralsRoute
  '/settings': typeof SettingsRoute
  '/stories': typeof StoriesRoute
  '/trends': typeof TrendsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/career-gps': typeof CareerGpsRoute
  '/challenges': typeof ChallengesRoute
  '/community': typeof CommunityRoute
  '/heatmap': typeof HeatmapRoute
  '/journey-map': typeof JourneyMapRoute
  '/mentors': typeof MentorsRoute
  '/office-hours': typeof OfficeHoursRoute
  '/referrals': typeof ReferralsRoute
  '/settings': typeof SettingsRoute
  '/stories': typeof StoriesRoute
  '/trends': typeof TrendsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/career-gps'
    | '/challenges'
    | '/community'
    | '/heatmap'
    | '/journey-map'
    | '/mentors'
    | '/office-hours'
    | '/referrals'
    | '/settings'
    | '/stories'
    | '/trends'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/career-gps'
    | '/challenges'
    | '/community'
    | '/heatmap'
    | '/journey-map'
    | '/mentors'
    | '/office-hours'
    | '/referrals'
    | '/settings'
    | '/stories'
    | '/trends'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/career-gps'
    | '/challenges'
    | '/community'
    | '/heatmap'
    | '/journey-map'
    | '/mentors'
    | '/office-hours'
    | '/referrals'
    | '/settings'
    | '/stories'
    | '/trends'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CareerGpsRoute: typeof CareerGpsRoute
  ChallengesRoute: typeof ChallengesRoute
  CommunityRoute: typeof CommunityRoute
  HeatmapRoute: typeof HeatmapRoute
  JourneyMapRoute: typeof JourneyMapRoute
  MentorsRoute: typeof MentorsRoute
  OfficeHoursRoute: typeof OfficeHoursRoute
  ReferralsRoute: typeof ReferralsRoute
  SettingsRoute: typeof SettingsRoute
  StoriesRoute: typeof StoriesRoute
  TrendsRoute: typeof TrendsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trends': {
      id: '/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof TrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referrals': {
      id: '/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof ReferralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office-hours': {
      id: '/office-hours'
      path: '/office-hours'
      fullPath: '/office-hours'
      preLoaderRoute: typeof OfficeHoursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentors': {
      id: '/mentors'
      path: '/mentors'
      fullPath: '/mentors'
      preLoaderRoute: typeof MentorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey-map': {
      id: '/journey-map'
      path: '/journey-map'
      fullPath: '/journey-map'
      preLoaderRoute: typeof JourneyMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heatmap': {
      id: '/heatmap'
      path: '/heatmap'
      fullPath: '/heatmap'
      preLoaderRoute: typeof HeatmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges': {
      id: '/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof ChallengesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career-gps': {
      id: '/career-gps'
      path: '/career-gps'
      fullPath: '/career-gps'
      preLoaderRoute: typeof CareerGpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CareerGpsRoute: CareerGpsRoute,
  ChallengesRoute: ChallengesRoute,
  CommunityRoute: CommunityRoute,
  HeatmapRoute: HeatmapRoute,
  JourneyMapRoute: JourneyMapRoute,
  MentorsRoute: MentorsRoute,
  OfficeHoursRoute: OfficeHoursRoute,
  ReferralsRoute: ReferralsRoute,
  SettingsRoute: SettingsRoute,
  StoriesRoute: StoriesRoute,
  TrendsRoute: TrendsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
